### PR TITLE
Bugfix - display transfer proj name if user can see it

### PR DESCRIPTION
**Pull request by joefitter**
* Updated to use establishmentName if not defined, fallback to another est

### CODE REVIEW

**Comment by lennym** [comment]
What's the bug?

**Comment by joefitter** [comment]
sorry - great commit message I know. if the transfer-to field wasn't completed, non-licence holders would always see "another establishment" instead of the current establishment

**Comment by joefitter** [comment]
in edit view

**Comment by lennym** [comment]
And this is because `localValue` isn't/wasn't set in a non-editing context?

It would be good to get an integration test covering this as well as there's been a couple of bugs around this component already.

**Comment by joefitter** [comment]
yeah good shout - I'll add some coverage. Previously we had `const localValue = useState(value || establishment.id)` but this was resulting in the useEffect detecting a change and marking the component as changed as soon as the page was loaded

**Comment by lennym** [comment]
> Previously we had `const localValue = useState(value || establishment.id)`

I don't see that in the red bit of the diff

**Comment by joefitter** [comment]
that was a previous bugfix

**Pull request merged**
