### PR TITLE
Bugfix - inform users of errors

### PR DESCRIPTION
**Pull request by joefitter**
previously we were swallowing errors in fields in a promise chain - inform users of these errors

### CODE REVIEW

**Comment by lennym** [comment]
Does this give a red banner, or the inline error component?

**Comment by lennym** [comment]
Also

**Comment by joefitter** [comment]
You get the read "toaster" message

**Comment by lennym** [comment]
How difficult would it be to convert it to the error component? This is good, but it's a lot more useful when we actually get bug reports to have more information.

**Pull request merged**
