### PR TITLE
PPL changes

### PR DESCRIPTION
**Pull request by pcuk1979**
Final (No. Really. Well maybe.) set of changes that I have been able to do myself.

Ones I can't will be uploaded to Jira in a ticket

### CODE REVIEW

**Comment by lennym** [comment]
This is going to need to wait until we can add markdown support to the non-rich-text-editor fields.

**Comment by pcuk1979** [comment]
No problemo

**Comment by joefitter** [comment]
_writes post-it_

**Comment by joefitter** [comment]
Related https://github.com/UKHomeOffice/react-components/pull/19

**Pull request merged**
